### ISSUE TITLE
Exception and endless response if you are request a non-valid download url

### ISSUE THREAD

**Issue by Augustus78** [silverwind/droppy#260]
If you open in your browser a download url that don’t existing droppy create this exception:
2016-06-07 12:24:20 [ERROR] =============== Uncaught exception! ===============
2016-06-07 12:24:20 [ERROR] TypeError: Cannot read property 'location' of undefined
    at handleFileRequest (/usr/lib/node_modules/droppy/server/server.js:718:39)
    at handleGET (/usr/lib/node_modules/droppy/server/server.js:534:5)
    at Server.onRequest (/usr/lib/node_modules/droppy/server/server.js:115:7)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:533:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
One way this is maybe good to complicate a brute force attack to find download urls, but for me it looks dirty and not wanted. Also I don’t know the side effect because I am not a Node developer.

With download url I mean urls like: ?$/fru7ksdvpdd (invalid/not existend) or simple ?$/

droppy 4.2.5
node 4.4.5

**Comment by Augustus78** [comment]
Thank you. Great and fast support. It works now without problem.
