### ISSUE TITLE
Direct download not working

### ISSUE THREAD

**Issue by platipo** [silverwind/droppy#265]
I have installed droppy in my Raspberry Pi 2 and connected an HHD. 
I noticed that when I try to download using the download button any file (even folders) the output always is a 18.23 kb file (hexdump output is the same for every downloaded file).
_sample_: [doc.zip](https://github.com/silverwind/droppy/files/478278/doc.zip)

Unlike the download button the share button retrive files correctly.

    node -v
    v6.6.0

**Comment by silverwind** [comment]
You're getting the site HTML for some reason. Is your version up to date? And if so, what's the URL of the download link? Oh, and can you reproduce in [the demo](https://droppy.silverwind.io)?

**Comment by platipo** [comment]
Yes, droppy is up to date

    $ droppy -v
    5.1.1

All the download links in my droppy behaves in the same way. None of them trigger correct download.

I forgot to mention that I use nginx proxy. Could nginx be the problem?

**Comment by silverwind** [comment]
> I forgot to mention that I use nginx proxy. Could nginx be the problem?

Possible, but I doubt it. I have [a sample nginx config](https://github.com/silverwind/droppy/wiki/Nginx-reverse-proxy) which you can take a look at. Note that all those proxy options aren't really required, they just help with long-running uploads.

Which URL you are seeing when hovering a download link. Is it `!/file/path/to/file`?

**Comment by platipo** [comment]
I checked the nginx config and it's exactly a copy of yours.

> Is it `!/file/path/to/file?`
Yes, it's exactly like this

**Comment by silverwind** [comment]
Can you show what is logged on the server when you click the link? Is there a 301 response maybe?

**Comment by silverwind** [comment]
Also, try manually opening the same URL, but with `file` replaced with `dl`, e.g: "!/dl/path/to/file".

**Comment by platipo** [comment]
Here is the log:
```
[INFO] `uws` module failed to build, falling back to `ws`
           .:.        __                              
    :::  .:::::.   --|  |---- ----- ----- ----- -- -- 
  ..:::..  :::    |  _  |   _|  _  |  _  |  _  |  |  |
   ':::'   :::    |_____|__| |_____|   __|   __|___  |
     '                             |__|  |__|  |_____|

 droppy 5.1.1 running on node 6.6.0
 config at /srv/droppy/config
 files at /mnt/NAStorage/droppy

2016-09-18 09:58:28 [INFO] Loading resources ...
2016-09-18 09:58:28 [INFO] Loading resources done
2016-09-18 09:58:29 [INFO] Listening on http://0.0.0.0:8989
2016-09-18 09:58:29 [INFO] Caching files ...
2016-09-18 09:58:29 [INFO] Caching files done
2016-09-18 09:58:30 [INFO] Ready for requests!
2016-09-18 09:58:30 [INFO] 127.0.0.1:46962 WebSocket [connected]
2016-09-18 09:58:30 [INFO] 127.0.0.1:46962 WebSocket [disconnected] (CSFR prevented or server restarted)
2016-09-18 09:58:30 [INFO] 127.0.0.1:46964 WebSocket [connected]
2016-09-18 09:58:31 [INFO] 192.168.0.8:49968 GET /!/token [200] [29ms]
2016-09-18 09:59:09 [INFO] 192.168.0.8:49968 GET /!/file/Dati appartamento/planimetria.jpg [301] [20ms]
2016-09-18 09:59:09 [INFO] 192.168.0.8:49968 GET / [200] [23ms]
2016-09-18 09:59:35 [INFO] 192.168.0.8:49968 GET /!/file/Work/doc/scheda_clienti.ods [301] [3ms]
2016-09-18 09:59:35 [INFO] 192.168.0.8:49968 GET / [200] [4ms]
```

Manually opening the download with `dl` it works
`2016-09-18 10:05:05 [INFO] 192.168.0.8:50122 GET /!/dl/Work/doc/scheda_clienti.ods [200] [25ms]
`

**Comment by gissehel** [comment]
@platipo 

The 18k page you get is the "login" page, so it seems when you click the link, you somewhat "lost" the credentials.

If the host is not the same on the address bar and on the "download link" (ex: https://www.example.com/#/ on the address bar and https://example.com/!/file.txt on the download link) it may create that kind of behavior (you're identified on example.com but not on www.example.com).

Can you check if the hosts are the same ?

**Comment by gissehel** [comment]
Oh! I've reproduced the problem too !!!

I'm usually using Firefox. And I don't have the problem in firefox. I tried on Chrome, and I reproduce the problem...

droppy 5.1.1
node 6.3.1
(I'm using latest official Docker image)
I'm behind a nginx reverse proxy + vhost

For the record, I've tried **Firefox**/Windows **48.0.2** and **Chrome**/Windows **53.0.2785.116 m**

I just also tried to directly export port 8989 (bypassing nginx) and I still reproduce the problem. So it's not nginx.

@platipo : Did you try on Firefox ?
@silverwind : Did you try on Chrome ?

**Comment by gissehel** [comment]
Server logs when using **Chrome**:

```
droppylog | 2016-09-18 09:35:06 [INFO] [::ffff:192.0.2.116]:63845 GET /!/file/folder/file.txt [301] [1ms]
droppylog | 2016-09-18 09:35:06 [INFO] [::ffff:192.0.2.116]:63845 GET / [200] [0ms]
```

Server logs when using **Firefox**:

```
droppylog | 2016-09-18 09:35:44 [INFO] [::ffff:192.0.2.116]:64551 GET /!/file/folder/file.txt [200] [1ms]
```

So the client code seems the same, just the server returns a 301 redirect to / when using Chrome. Should be a slightly different header. Didn't sniff it yet.

**Comment by platipo** [comment]
URL page: https://example.com#/ (not https://example.com/#/)
URL download file: https://example.com/!/file/path/to/file
URL download dir: https://example.com/!/zip/path/to/dir

I use **Vivaldi**/Linux 1.4.589.15 and **Chromium**/Windows 55.0.2864.2
Never tried on Firefox, but I'll do ASAP.

**Comment by silverwind** [comment]
Still cannot reproduce in Chrome unfortunately. 

It may be related to cookies, as I recently changed the `path` attribute so the session cookie named `s` is scoped to the path (or paths below) that was present when logging in.

Can you go to `chrome://settings/siteSettings/cookies` and show what's in the `path` property of the cookie? Also, it might help if you just clear all cookies for that site and log in again.

![](https://cloud.githubusercontent.com/assets/115237/18615156/4567c8c6-7d9f-11e6-97fd-5bbc410908cd.png)

**Comment by silverwind** [comment]
Oh wait, I actually can reproduce in Chrome, checking..

**Comment by silverwind** [comment]
Looks like we found a Chrome bug, when `SameSite=strict` is set on the cookie, it is not sent along with requests when clicking a link with a `download` attribute.

I'll work around by not setting the `download` attribute and instead trigger the download on the HTTP response.

**Comment by silverwind** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=648043.

**Comment by silverwind** [comment]
Released 5.1.2 with the fix.

**Comment by platipo** [comment]
Still not working on Vivaldi 1.4.589.15-1/Linux but now download button trigger no download
```
           .:.        __                              
    :::  .:::::.   --|  |---- ----- ----- ----- -- -- 
  ..:::..  :::    |  _  |   _|  _  |  _  |  _  |  |  |
   ':::'   :::    |_____|__| |_____|   __|   __|___  |
     '                             |__|  |__|  |_____|

 droppy 5.1.2 running on node 6.6.0
 config at /srv/droppy/config
 files at /srv/droppy/files

2016-09-18 15:04:47 [INFO] Loading resources ...
2016-09-18 15:04:48 [INFO] Loading resources done
2016-09-18 15:04:48 [INFO] Listening on http://0.0.0.0:8989
2016-09-18 15:04:48 [INFO] Caching files ...
2016-09-18 15:04:48 [INFO] Caching files done
2016-09-18 15:04:49 [INFO] Ready for requests!
2016-09-18 15:04:49 [INFO] 192.168.0.8:55060 GET / [200] [48ms]
2016-09-18 15:04:49 [INFO] 192.168.0.8:55060 GET /!/res/style.css [304] [7ms]
2016-09-18 15:04:49 [INFO] 192.168.0.8:55060 GET /!/res/client.js [304] [3ms]
2016-09-18 15:04:54 [INFO] 192.168.0.8:55060 POST /!/login [200] [33ms] User 'enrico' authenticated
2016-09-18 15:04:54 [INFO] 192.168.0.8:55060 GET / [200] [6ms]
2016-09-18 15:04:54 [INFO] 192.168.0.8:55060 GET /!/res/style.css [304] [1ms]
2016-09-18 15:04:54 [INFO] 192.168.0.8:55060 GET /!/res/sprites.png [304] [1ms]
2016-09-18 15:04:54 [INFO] 192.168.0.8:55056 GET /!/res/client.js [304] [0ms]
2016-09-18 15:04:54 [INFO] 192.168.0.8:55056 GET /!/res/font.woff2 [304] [0ms]
2016-09-18 15:04:54 [INFO] 127.0.0.1:47246 WebSocket [connected]
2016-09-18 15:04:54 [INFO] 192.168.0.8:55056 GET /!/token [200] [5ms]
2016-09-18 15:05:01 [INFO] 192.168.0.8:55056 GET / [200] [6ms]
2016-09-18 15:05:10 [INFO] 192.168.0.8:55076 GET /!/dl/Work/doc/scheda_clienti.ods [301] [7ms]
2016-09-18 15:05:10 [INFO] 192.168.0.8:55076 GET / [200] [3ms]
2016-09-18 15:05:31 [INFO] 192.168.0.8:55076 GET /!/zip/Work/doc [301] [6ms]
2016-09-18 15:05:31 [INFO] 192.168.0.8:55076 GET / [200] [5ms]
```
Working on Chrome 53.0.2785.116 m
```
2016-09-18 15:12:16 [INFO] 192.168.0.11:49185 GET /!/dl/Dati appartamento/planimetria.pdf [200] [7ms]
```
Working on Mozilla 48.0/Android (zip raises exception):
```
2016-09-18 15:07:19 [INFO] 192.168.0.6:48633 GET /!/dl/Dati appartamento/planimetria.jpg [200] [35ms]
2016-09-18 15:30:23 [INFO] 192.168.0.6:48658 GET /!/zip/Dati appartamento [200] [2ms]
2016-09-18 15:30:23 [INFO] Streaming zip of /Dati appartamento
2016-09-18 15:30:23 [ERROR] =============== Uncaught exception! ===============
2016-09-18 15:30:23 [ERROR] invalid relative path: ../../../mnt/NAStorage/droppy/Dati appartamento/bollette-eletticità.pdf
    at validateMetadataPath (/usr/local/lib/node_modules/droppy/node_modules/yazl/index.js:352:59)
    at ZipFile.addFile (/usr/local/lib/node_modules/droppy/node_modules/yazl/index.js:24:18)
    at ReaddirpReadable.<anonymous> (/usr/local/lib/node_modules/droppy/server/server.js:1117:17)
    at emitOne (events.js:96:13)
    at ReaddirpReadable.emit (events.js:188:7)
    at readableAddChunk (/usr/local/lib/node_modules/droppy/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:213:18)
    at ReaddirpReadable.Readable.push (/usr/local/lib/node_modules/droppy/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:172:10)
    at ReaddirpReadable.proto._processEntry (/usr/local/lib/node_modules/droppy/node_modules/readdirp/stream-api.js:52:8)
    at /usr/local/lib/node_modules/droppy/node_modules/readdirp/readdirp.js:243:15
    at Array.forEach (native)
```
Working on Midori 0.5.11-4/Linux (same):
```
2016-09-18 15:18:18 [INFO] 192.168.0.8:55210 GET /!/zip/Dati appartamento [200] [4ms]
2016-09-18 15:18:18 [INFO] Streaming zip of /Dati appartamento
2016-09-18 15:18:18 [ERROR] =============== Uncaught exception! ===============
2016-09-18 15:18:18 [ERROR] invalid relative path: ../../../mnt/NAStorage/droppy/Dati appartamento/bollette-eletticità.pdf
    at validateMetadataPath (/usr/local/lib/node_modules/droppy/node_modules/yazl/index.js:352:59)
    at ZipFile.addFile (/usr/local/lib/node_modules/droppy/node_modules/yazl/index.js:24:18)
    at ReaddirpReadable.<anonymous> (/usr/local/lib/node_modules/droppy/server/server.js:1117:17)
    at emitOne (events.js:96:13)
    at ReaddirpReadable.emit (events.js:188:7)
    at readableAddChunk (/usr/local/lib/node_modules/droppy/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:213:18)
    at ReaddirpReadable.Readable.push (/usr/local/lib/node_modules/droppy/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:172:10)
    at ReaddirpReadable.proto._processEntry (/usr/local/lib/node_modules/droppy/node_modules/readdirp/stream-api.js:52:8)
    at /usr/local/lib/node_modules/droppy/node_modules/readdirp/readdirp.js:243:15
    at Array.forEach (native)
2016-09-18 15:18:25 [INFO] 192.168.0.8:55214 GET /!/dl/Dati appartamento/bollette-eletticità.pdf [200] [3ms]
```
Working on Chromium 51.0.2682.0/Windows (same):
```
2016-09-18 15:22:58 [INFO] 192.168.0.11:49203 GET /!/dl/Dati appartamento/bollette-eletticità.pdf [200] [28ms]
2016-09-18 15:23:02 [INFO] 192.168.0.11:49203 GET /!/zip/Dati appartamento [200] [3ms]
2016-09-18 15:23:02 [INFO] Streaming zip of /Dati appartamento
2016-09-18 15:23:02 [ERROR] =============== Uncaught exception! ===============
2016-09-18 15:23:02 [ERROR] invalid relative path: ../../../mnt/NAStorage/droppy/Dati appartamento/bollette-eletticità.pdf
    at validateMetadataPath (/usr/local/lib/node_modules/droppy/node_modules/yazl/index.js:352:59)
    at ZipFile.addFile (/usr/local/lib/node_modules/droppy/node_modules/yazl/index.js:24:18)
    at ReaddirpReadable.<anonymous> (/usr/local/lib/node_modules/droppy/server/server.js:1117:17)
    at emitOne (events.js:96:13)
    at ReaddirpReadable.emit (events.js:188:7)
    at readableAddChunk (/usr/local/lib/node_modules/droppy/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:213:18)
    at ReaddirpReadable.Readable.push (/usr/local/lib/node_modules/droppy/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:172:10)
    at ReaddirpReadable.proto._processEntry (/usr/local/lib/node_modules/droppy/node_modules/readdirp/stream-api.js:52:8)
    at /usr/local/lib/node_modules/droppy/node_modules/readdirp/readdirp.js:243:15
    at Array.forEach (native)
```

**Comment by silverwind** [comment]
@platipo maybe your nginx is caching the old site? Try a CTRL-F5 or CTRL-Shift-R. I'll investigate the zip issue.

**Comment by silverwind** [comment]
@platipo is `/srv/droppy/files` a symlink to `../../../mnt/NAStorage/droppy`?

**Comment by platipo** [comment]
Restarted nginx and cleared cache now download of files work on Vivaldi.

@silverwind Yes, it's a symlink

    lrwxrwxrwx 1 droppy droppy 22 Aug  9 15:30 /srv/droppy/files -> /mnt/NAStorage/droppy/

**Comment by silverwind** [comment]
@platipo thanks. Symlinks like that shall be handled correctly now, though I recommend you just launch with `droppy -f /mnt/NAStorage/droppy`. 5.1.3 is building with that fix.

**Comment by platipo** [comment]
@silverwind thank you! Great job :+1: 
Now zip works fine

```
2016-09-18 17:05:45 [INFO] 192.168.0.6:48720 GET /!/zip/Dati appartamento [200] [16ms]
2016-09-18 17:05:45 [INFO] Streaming zip of /Dati appartamento
```

In Vivaldi neither file nor zip downloads works yet

**Comment by silverwind** [comment]
> In Vivaldi neither file nor zip downloads works yet

What's the issue? Everything seems to work fine in Vivaldi on Windows for me.

**Comment by platipo** [comment]
My bad, awesome work man! :rocket: :+1:

**Comment by vivagonna** [comment]
Hi,

I seem to get a similar problem. The difference is: I can trigger the download with ctrl + left click on "download" button. According to the log, it didn't send any request when "download" button is clicked directly. It is 6.2.1 version. In fact, I have two instances on different VPS, this one, which has the problem, was newly installed; while the other one, which was just updated to 6.2.1, doesn't have this problem. So, Maybe there is something wrong with my client side js? Thanks.

**Comment by silverwind** [comment]
Ah, this is a issue introduced in 6.2.1 caused by a security measure inadvertently blocking downloads. This is visible in the browser console:

```
Refused to frame '<url>' because it violates the following Content Security Policy directive: "child-src 'none'". Note that 'frame-src' was not explicitly set, so 'child-src' is used as a fallback.
```

Fixed in https://github.com/silverwind/droppy/commit/aa6895f5340f163ff88db9f409010f8ac0f231fb, please update to v6.2.2.

**Comment by vivagonna** [comment]
@silverwind Great! Thanks.
