### ISSUE TITLE
Since Docker image 5.0.13 containers fails randomly at start (about half of the time).

### ISSUE THREAD

**Issue by gissehel** [silverwind/droppy#267]
When launching droppy image since 5.0.13 (found by dichotomy), it may go well:

```
[INFO] `uws` module failed to build, falling back to `ws`
           .:.        __
    :::  .:::::.   --|  |---- ----- ----- ----- -- --
  ..:::..  :::    |  _  |   _|  _  |  _  |  _  |  |  |
   ':::'   :::    |_____|__| |_____|   __|   __|___  |
     '                             |__|  |__|  |_____|

 droppy 5.0.13 running on node 6.3.1
 config at /config
 files at /files

2016-09-19 06:25:48 [INFO] Loading resources ...
2016-09-19 06:25:48 [INFO] Loading resources done
2016-09-19 06:25:48 [INFO] Listening on http://[::]:8989
2016-09-19 06:25:48 [INFO] Caching files ...
2016-09-19 06:25:48 [INFO] Caching files done
2016-09-19 06:25:48 [INFO] Ready for requests!
2016-09-19 06:25:48 [INFO] Received SIGINT - Shutting down ...
```

or go totally wrong:

```
[INFO] `uws` module failed to build, falling back to `ws`
           .:.        __
    :::  .:::::.   --|  |---- ----- ----- ----- -- --
  ..:::..  :::    |  _  |   _|  _  |  _  |  _  |  |  |
   ':::'   :::    |_____|__| |_____|   __|   __|___  |
     '                             |__|  |__|  |_____|

 droppy 5.0.13 running on node 6.3.1
 config at /config
 files at /files

Segmentation fault (core dumped)
```

(To actually see the **segmentation fault**, I started /bin/sh then launched `/start.sh` manually. For the records, there is actually no `core` to be found anywhere on the container file system)

**Comment by gissehel** [comment]
After a long investigation, found the problem. Here are some clues of the investigation with raw error message for Google to index in order to help future people searching Google with error messages:

* First, the problem apeared in the same release where uws was added (in fact, 5.0.10 worked fine, 5.0.11 and 5.0.12 didn't work at all because uws wasn't installed properly and uws was required, 5.0.13 worked "randomly" because uws wasn't mandatory anymore, using ws as a fallback, but the probing for uws seems to be the code that generates later the core dump)
* On 5.0.13 and later, requiering `uws` in node result in the following message:
```
    /app # node
    > require('uws')
    Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
        at e (/app/node_modules/uws/uws.js:21:19)
        at Object.<anonymous> (/app/node_modules/uws/uws.js:25:3)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at repl:1:1
```
* It appears that uws is sheapped with .cpp sources, and rely on the presence of a C++11 compiler (like gpp recent version) which is obviously not present in the small footprint alpine-node base image the docker container use, but it also shipped with precompiled binaries for severals well used environnement like linux/osx/win. On my system, it's linux + 48. What is relly called inside uws is a require on the binary file `uws_linux_48.node` which is equivalent to:
```
    /app # node
    > require('./node_modules/uws/uws_linux_48.node')
```
* When I launch that on my system, I've got randomly two results, either:
```
    /app # node
    > require('./node_modules/uws/uws_linux_48.node')
    Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/uws/uws_linux_48.node)
        at Error (native)
        at Object.Module._extensions..node (module.js:568:18)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at repl:1:1
        at sigintHandlersWrap (vm.js:32:31)
        at sigintHandlersWrap (vm.js:96:12)
```
* Or:
```
    /app # node
    > require('./node_modules/uws/uws_linux_48.node')
    Segmentation fault (core dumped)
```
* So the problem isn't that "compilation µWebSockets has failed" (not a problem, binaries are here for that) or that there is no binaries for the system. It's the binaries are linked to **ld-linux-x86-64.so.2** which isn't present on the system.
* After random Google search about that, found that **`apk install libc6-compat`** is just what is needed.

I'm preparing a pull request to fix that.

**Comment by silverwind** [comment]
Awesome research. 👏

@alexhultman: anything that could be done from your side to improve compatibilty of uws for [musl](https://www.musl-libc.org/)-based systems like Alpine? A hard dependency in libc is certainly problematic.

**Comment by silverwind** [comment]
Nevermind, I think the root issue is that that docker image I'm using isn't including the necessary build tools (I assumed it did), so it's falling back to the glibc prebuilds. I'll fix it properly by making sure uws can build the module correctly.

**Comment by silverwind** [comment]
Okay the 5.1.7 image should solve this properly. I install build tools, run `npm install` and then uninstall the tools again. Consolidating the Docker commands into one also reduced the compressed image size from 28 MB to 23 MB by consolidating commands.

**Comment by alexhultman** [comment]
I don't know if this helps but the latest uws release should run out of the box on more Linux systems (like Debian and other such systems which comes with ancient compilers and libstdc++'s). Maybe it helps issues like these too, I don't know if that libc is compatible with the one uws needs, maybe.

This is the current output of LDD:

	linux-vdso.so.1 (0x00007ffe1ef35000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f50583dd000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f505801c000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a45a46e000)

**Comment by silverwind** [comment]
If only it would build. Here's 0.10.6 on Debian 7 (gcc 4.7.2, libc.so.6):
````
make: Entering directory `/app/node_modules/uws/build'
make: Warning: File `../src/Extensions.cpp' has modification time 9.7e+04 s in the future
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
In file included from ../src/WebSocket.h:4:0,
                 from ../src/Group.h:4,
                 from ../src/Group.cpp:1:
../src/WebSocketProtocol.h: In static member function 'static size_t uWS::WebSocketProtocol<isServer>::formatMessage(char*, const char*, size_t, uWS::OpCode, size_t, bool)':
../src/WebSocketProtocol.h:273:38: error: 'UINT16_MAX' was not declared in this scope
make: *** [Release/obj.target/uws/src/Group.o] Error 1
make: Leaving directory `/app/node_modules/uws/build'
````

**Comment by alexhultman** [comment]
Does it work if you add `#include <cstdint>` in the top of WebSocketProtocol.h?

**Comment by silverwind** [comment]
No, but what did help was `#define __STDC_LIMIT_MACROS` before the other includes. Now I'm getting:

````
make: Entering directory `/app/node_modules/uws/build'
make: Warning: File `../src/Extensions.cpp' has modification time 9.6e+04 s in the future
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
  CXX(target) Release/obj.target/uws/src/WebSocketImpl.o
In file included from ../src/Hub.h:5:0,
                 from ../src/WebSocketImpl.cpp:1:
../src/Node.h: In member function 'bool uS::Node::listen(int, uS::TLS::Context, int, uS::NodeData*, void*)':
../src/Node.h:147:46: error: 'SO_REUSEPORT' was not declared in this scope
In file included from ../src/WebSocketImpl.cpp:1:0:
../src/Hub.h: At global scope:
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Hub.h:32:33: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
In file included from ../src/WebSocket.h:4:0,
                 from ../src/Group.h:4,
                 from ../src/Hub.h:4,
                 from ../src/WebSocketImpl.cpp:1:
../src/WebSocketProtocol.h: In instantiation of 'static uWS::WebSocketProtocol<isServer>::CloseFrame uWS::WebSocketProtocol<isServer>::parseClosePayload(char*, size_t) [with bool isServer = true; size_t = long unsigned int]':
../src/WebSocketImpl.cpp:104:16:   required from here
../src/WebSocketProtocol.h:247:26: warning: missing initializer for member 'uWS::WebSocketProtocol<true>::CloseFrame::code' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:247:26: warning: missing initializer for member 'uWS::WebSocketProtocol<true>::CloseFrame::message' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:247:26: warning: missing initializer for member 'uWS::WebSocketProtocol<true>::CloseFrame::length' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:253:25: warning: missing initializer for member 'uWS::WebSocketProtocol<true>::CloseFrame::code' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:253:25: warning: missing initializer for member 'uWS::WebSocketProtocol<true>::CloseFrame::message' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:253:25: warning: missing initializer for member 'uWS::WebSocketProtocol<true>::CloseFrame::length' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h: In instantiation of 'void uWS::WebSocketProtocol<isServer>::consume(char*, unsigned int, void*) [with bool isServer = true]':
../src/WebSocketImpl.cpp:104:16:   required from here
../src/WebSocketProtocol.h:326:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../src/WebSocketProtocol.h:341:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../src/WebSocketProtocol.h:346:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../src/WebSocketProtocol.h: In instantiation of 'static uWS::WebSocketProtocol<isServer>::CloseFrame uWS::WebSocketProtocol<isServer>::parseClosePayload(char*, size_t) [with bool isServer = false; size_t = long unsigned int]':
../src/WebSocketImpl.cpp:105:16:   required from here
../src/WebSocketProtocol.h:247:26: warning: missing initializer for member 'uWS::WebSocketProtocol<false>::CloseFrame::code' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:247:26: warning: missing initializer for member 'uWS::WebSocketProtocol<false>::CloseFrame::message' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:247:26: warning: missing initializer for member 'uWS::WebSocketProtocol<false>::CloseFrame::length' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:253:25: warning: missing initializer for member 'uWS::WebSocketProtocol<false>::CloseFrame::code' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:253:25: warning: missing initializer for member 'uWS::WebSocketProtocol<false>::CloseFrame::message' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h:253:25: warning: missing initializer for member 'uWS::WebSocketProtocol<false>::CloseFrame::length' [-Wmissing-field-initializers]
../src/WebSocketProtocol.h: In instantiation of 'void uWS::WebSocketProtocol<isServer>::consume(char*, unsigned int, void*) [with bool isServer = false]':
../src/WebSocketImpl.cpp:105:16:   required from here
../src/WebSocketProtocol.h:326:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../src/WebSocketProtocol.h:341:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../src/WebSocketProtocol.h:346:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
make: *** [Release/obj.target/uws/src/WebSocketImpl.o] Error 1
make: Leaving directory `/app/node_modules/uws/build'
````

**Comment by silverwind** [comment]
Oh, and here's the `ldd` showing a GLIBC error:

```
root@299874ffe56a:/app/node_modules/uws# ldd uws_linux_48.node
./uws_linux_48.node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./uws_linux_48.node)
	linux-vdso.so.1 =>  (0x00007fff46fa3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa13a801000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa13a474000)
	/lib64/ld-linux-x86-64.so.2 (0x000055b1f8ef6000)
```

**Comment by alexhultman** [comment]
That's unfortunate. Seems like we need to link statically to libc also.

**Comment by DomHoney** [comment]
Were there any updates for this? Currently investigating using uws in a similar environment and getting the same problems.

Wondering if I should be bothering with Alpine.

_Apologies if I'm going against any resurrecting thread etiquette_

Alpine 3.6
NODE_VERSION 8.9.3
uws 8.14.1

`require('./node_modules/uws/uws_linux_57.node')   
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /soft352-project/node_modules/uws/uws_linux_57.node)   
    at Object.Module._extensions..node (module.js:664:18)   
    at Module.load (module.js:554:32)   
    at tryModuleLoad (module.js:497:12)   
    at Function.Module._load (module.js:489:3)   
    at Module.require (module.js:579:17)   
    at require (internal/module.js:11:18)   
    at repl:1:1   
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)   
    at REPLServer.defaultEval (repl.js:240:29)   
    at bound (domain.js:301:14)   
`
