### ISSUE TITLE
Downloading zips not working inside symlink

### ISSUE THREAD

**Issue by hmercade** [silverwind/droppy#273]
So I have my root with symlinks to other directories.
When I try to zip a directory inside a symlink dir, zip fails.
File downloading is working as expected.

This is under linux, with the latest version pulled from master.
Here I attach the log messages generated when clicking the zip&download dir inside symlink.

I hope this can be of help. Thank you for all your amazing work.

```
3|droppy   | 2016-10-01 19:55:50 [INFO] Caching files done
3|droppy   | 2016-10-01 19:55:52 [INFO] Ready for requests!
3|droppy   | 2016-10-01 19:55:52 [INFO] 127.0.0.1:38334 WebSocket [connected]
3|droppy   | 2016-10-01 19:55:53 [INFO] 127.0.0.1:38334 WebSocket [disconnected] (CSFR prevented or server restarted)
3|droppy   | 2016-10-01 19:55:53 [INFO] 127.0.0.1:38341 WebSocket [connected]
3|droppy   | 2016-10-01 19:55:53 [INFO] 83.59.63.64:38342 GET /!/token [200] [18ms]
3|droppy   | 2016-10-01 19:56:10 [INFO] 83.59.63.64:38362 GET /!/zip/symlink/folder [200] [13ms]
3|droppy   | 2016-10-01 19:56:10 [INFO] Streaming zip of /symlink/folder
3|droppy   | Error: invalid relative path: ../../droppytest/folder/filea
3|droppy   |     at validateMetadataPath (/home/hector/web/droppy/node_modules/yazl/index.js:352:59)
3|droppy   |     at ZipFile.addFile (/home/hector/web/droppy/node_modules/yazl/index.js:24:18)
3|droppy   |     at ReaddirpReadable.<anonymous> (/home/hector/web/droppy/server/server.js:1113:17)
3|droppy   |     at emitOne (events.js:96:13)
3|droppy   |     at ReaddirpReadable.emit (events.js:188:7)
3|droppy   |     at readableAddChunk (/home/hector/web/droppy/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:213:18)
3|droppy   |     at ReaddirpReadable.proto._processEntry (/home/hector/web/droppy/node_modules/readdirp/stream-api.js:52:8)
3|droppy   |     at /home/hector/web/droppy/node_modules/readdirp/readdirp.js:243:15
3|droppy   |     at Array.forEach (native)
3|droppy   |     at /home/hector/web/droppy/node_modules/readdirp/readdirp.js:241:12
3|droppy   | 2016-10-01 19:56:10 [ERROR] =============== Uncaught exception! ===============
3|droppy   | 2016-10-01 19:56:10 [ERROR] invalid relative path: ../../droppytest/folder/filea
3|droppy   |     at validateMetadataPath (/home/hector/web/droppy/node_modules/yazl/index.js:352:59)
3|droppy   |     at ZipFile.addFile (/home/hector/web/droppy/node_modules/yazl/index.js:24:18)
3|droppy   |     at ReaddirpReadable.<anonymous> (/home/hector/web/droppy/server/server.js:1113:17)
3|droppy   |     at emitOne (events.js:96:13)
3|droppy   |     at ReaddirpReadable.emit (events.js:188:7)
3|droppy   |     at readableAddChunk (/home/hector/web/droppy/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:213:18)
3|droppy   |     at ReaddirpReadable.proto._processEntry (/home/hector/web/droppy/node_modules/readdirp/stream-api.js:52:8)
3|droppy   |     at /home/hector/web/droppy/node_modules/readdirp/readdirp.js:243:15
3|droppy   |     at Array.forEach (native)
3|droppy   |     at /home/hector/web/droppy/node_modules/readdirp/readdirp.js:241:12
```

**Comment by silverwind** [comment]
Thanks for reporting. The issue was a confusion of resolved and unresolved paths. The fix turned out nicely and it even simplified the zip creation code a bit. Thanks for reporting!

**Comment by silverwind** [comment]
Yesterday's fix had some bugs, so make sure to update to 5.1.14.

**Comment by hmercade** [comment]
Wow so fast! Thanks yo you for your amazing work!
