### ISSUE TITLE
Docker wont start without IPv6 address

### ISSUE THREAD

**Issue by joltcan** [silverwind/droppy#297]
See this more as a FYI, but my QNAP NAS doesn't have IPv6 on, and hence the "::" address in the config doesn't start:

```
2017-04-05 10:38:39 [INFO] Loading resources ...                                                                  
2017-04-05 10:38:39 [INFO] Loading resources done                                                                 
2017-04-05 10:38:39 [INFO] Failed to bind to :::8989. Protocol unsupported.                                       
2017-04-05 10:38:39 [ERROR] listen EAFNOSUPPORT :::8989                                                           
    at Object.exports._errnoException (util.js:1034:11)                                                           
    at exports._exceptionWithHostPort (util.js:1057:20)                                                           
    at Server._listen2 (net.js:1252:19)                                                                           
    at listen (net.js:1301:10)                                                                                    
    at doListening (net.js:1416:7)                                                                                
    at _combinedTickCallback (internal/process/next_tick.js:83:11)                                                
    at process._tickCallback (internal/process/next_tick.js:104:9)       
```
Not a huge problem, just removed that part from the config manually after the first run, and now it starts ok.

**Comment by silverwind** [comment]
Should be fixed in v6.3.10, it shouldn't abort anymore, unless there are no listeners bound.

**Comment by achaiah** [comment]
@joltcan  Can you please tell me how you solved this issue?  It appears again in the latest silverwind docker build on dockerhub :( :( :(

**Comment by silverwind** [comment]
@achaiah can you show the output of `docker inspect <container>`?

**Comment by joltcan** [comment]
@achaiah: The way I solved it was that I just removed the ipv6 address of the host part of the config (I mapped /config to a dir on my drive). Listeners just look like this now:
```
"listeners": [
    {
      "host": [
        "0.0.0.0"
      ],
      "port": 8989,
      "protocol": "http"
    }
```

**Comment by achaiah** [comment]
@joltcan 
Thanks for the config, that solved my problem!

@silverwind 
It was the IPv6 issue just like @joltcan noted above. Perhaps something can be changed so that droppy can start in IPv4-only servers without trouble.

**Comment by silverwind** [comment]
It's partly a Node.js issue but I've worked around it by changing the default `host` option in https://github.com/silverwind/droppy/commit/8ffa656575877756fefed8f479ed7e98866bfd46 and supressing any misleading error messages that can result from attempting to bind the same socket/port twice or on cases where IPv6 is disabled in the kernel.
