### ISSUE TITLE
Keep logging "Watch error"

### ISSUE THREAD

**Issue by t-k-** [silverwind/droppy#307]
When droppy starts to serve, it keeps logging "Watch error", each line is something like below:
```
2017-06-01 15:54:46 [ERROR] watch /home/tk/tksync/var/cowpie_x/npm/node_modules/nodegit/vendor/libgit2/tests/resources/submod2/.gitted/modules/sm_unchanged/logs/refs/remotes/origin/HEAD ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/home/tk/Desktop/blog-feeds-incr-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/tk/Desktop/blog-feeds-incr-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/tk/Desktop/blog-feeds-incr-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/tk/Desktop/blog-feeds-incr-sync/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/tk/Desktop/blog-feeds-incr-sync/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Is this a problem? Can I disable FSWatcher?

Environment:
droppy@6.3.18
node@v6.5.0

**Comment by silverwind** [comment]
Why is droppy not in these paths in your stack trace? Are you using it as a module?

As for the error, I can probably add a option to disable file system watching entirely. It should still work without it, but it won't notice changes that are made to the file system directly.

**Comment by t-k-** [comment]
I have no idea. I first `cd` to `node_modules/.bin` and run `./droppy` directly.

I think not every user needs file system watcher, in my case, I do not require droppy to reflect file changes instantly, I rather prefer there is a way to disable watcher so that it takes much less time to wait these watcher being setup, BTW my root directory has a very deep hierarchy, a great number of files. It takes considerable time for droppy to go over all these files and setup the watchers, before it is able to handle the first GET request.

**Comment by silverwind** [comment]
Regarding ENOSPC you could attempt https://stackoverflow.com/a/32600959/808699.

But I agree, some control on what is indexed is probably a good idea. I'm thinking about adding a `ignore` option where you can specify patterns like `.git` which should not be available.

Another improvement will be a option to read files on-demand as the user switches through directories. This has the drawback a short delay when navigating the directories.

**Comment by silverwind** [comment]
I added a `watch` option to disable watching entirely. Also the new `ignorePattern` option might be helpful to you when you want to exclude certain patterns from being indexed.

I opted to not work on adding a option to disable the file tree in-memory cache as the change required is far from trivial.

**Comment by t-k-** [comment]
@silverwind Thank you for making such a great software even better.
