### ISSUE TITLE
systemd service keeps failing

### ISSUE THREAD

**Issue by platipo** [silverwind/droppy#323]
Everything worked fine for long time until two weeks ago when I discovered the systemd service continuously failing
```
# systemctl restart droppy
# systemctl status droppy
* droppy.service - droppy
   Loaded: loaded (/etc/systemd/system/droppy.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2017-08-05 13:12:16 CEST; 2s ago
 Main PID: 416 (node)
    Tasks: 6 (limit: 4915)
   CGroup: /system.slice/droppy.service
           `-416 node /usr/sbin/droppy start -c /srv/droppy/config -f /srv/droppy/files
# systemctl status droppy
* droppy.service - droppy
   Loaded: loaded (/etc/systemd/system/droppy.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-08-05 13:12:21 CEST; 783ms ago
  Process: 416 ExecStart=/usr/bin/env droppy start -c /srv/droppy/config -f /srv/droppy/files (code=exited, status=1/FAILURE)
 Main PID: 416 (code=exited, status=1/FAILURE)

Aug 05 13:12:21 xxxx systemd[1]: droppy.service: Main process exited, code=exited, status=1/FAILURE
Aug 05 13:12:21 xxxx systemd[1]: droppy.service: Unit entered failed state.
Aug 05 13:12:21 xxxx systemd[1]: droppy.service: Failed with result 'exit-code'.
```
But if I start it as `droppy start -c /srv/droppy/config -f /srv/droppy/files` everything works fine.

System info:
```
# uname -a
Linux skydata 4.9.40-1-ARCH #1 SMP Tue Aug 1 00:59:10 UTC 2017 armv7l GNU/Linux
# npm -v
5.3.0
# node -v
v8.2.1
```

P.S. I followed the wiki to configure the service

**Comment by silverwind** [comment]
What does the journal say? Run

````sh
journalctl -u droppy -n 500 -o cat -e
````

(feel free to remove unrelated lines)

**Comment by platipo** [comment]
Save thing over and over
```
# journalctl -u droppy -n 500 -o cat -e
droppy.service: Unit entered failed state.
droppy.service: Failed with result 'exit-code'.
droppy.service: Main process exited, code=exited, status=126/n/a
droppy.service: Unit entered failed state.
droppy.service: Failed with result 'exit-code'.
droppy.service: Main process exited, code=exited, status=126/n/a
droppy.service: Unit entered failed state.
droppy.service: Failed with result 'exit-code'.
droppy.service: Main process exited, code=exited, status=126/n/a
droppy.service: Unit entered failed state.
droppy.service: Failed with result 'exit-code'.
droppy.service: Main process exited, code=exited, status=126/n/a
droppy.service: Unit entered failed state.
droppy.service: Failed with result 'exit-code'.
droppy.service: Main process exited, code=exited, status=126/n/a
...
droppy.service: Unit entered failed state.
droppy.service: Failed with result 'exit-code'.
droppy.service: Start request repeated too quickly.
Failed to start droppy.
[Here I disabled restart=always]
droppy.service: Unit entered failed state.
droppy.service: Failed with result 'exit-code'.
droppy.service: Main process exited, code=exited, status=1/FAILURE
...
```

**Comment by silverwind** [comment]
Hmm, I think there might be something wrong with your path. Try changing `ExecStart` in `/etc/systemd/system/droppy.service` to:

```
ExecStart /srv/droppy/droppy.js start -c /srv/droppy/config -f /srv/droppy/files
```

**Comment by platipo** [comment]
But I have no `droppy.js` in `/srv/droppy`
```
# ls /srv/droppy/
config  config.json  db.json  files
```
and
```
# which droppy
/usr/bin/droppy
```

**Comment by silverwind** [comment]
Ah, yes of course. Replace `/srv/droppy/droppy.js` with `/usr/bin/droppy`. Running this directly will probably also give you some error details:

````
/usr/bin/droppy start -c /srv/droppy/config -f /srv/droppy/files
````

**Comment by platipo** [comment]
Edited and...
```
# systemctl daemon-reload
# systemctl start droppy
# systemctl status droppy.service
* droppy.service - droppy
   Loaded: loaded (/etc/systemd/system/droppy.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-08-05 17:28:55 CEST; 8s ago
  Process: 1255 ExecStart=/usr/bin/droppy start -c /srv/droppy/config -f /srv/droppy/files (code=exited, status=1/FAILURE)
 Main PID: 1255 (code=exited, status=1/FAILURE)

Aug 05 17:28:55 xxxx systemd[1]: droppy.service: Main process exited, code=exited, status=1/FAILURE
Aug 05 17:28:55 xxxx systemd[1]: droppy.service: Unit entered failed state.
Aug 05 17:28:55 xxxx systemd[1]: droppy.service: Failed with result 'exit-code'.
```
Dump of service:
```
# cat /etc/systemd/system/droppy.service
[Unit]
Description=droppy
After=network.target

[Service]
ExecStart=/usr/bin/droppy start -c /srv/droppy/config -f /srv/droppy/files
WorkingDirectory=/srv/droppy
Environment="NODE_ENV=production"
#Restart=always
User=droppy
Group=droppy
SyslogIdentifier=droppy

[Install]
WantedBy=multi-user.target
```

**Comment by silverwind** [comment]
Try adding this to the `[Service]` section to see what's happening (I also added that in the wiki): 

```
StandardOutput=journal
```

Then, restart the service and you should see a bit more in `journalctl -u droppy -n 100 -o cat -e`.

**Comment by platipo** [comment]
Nothing more than:
```
droppy.service: Main process exited, code=exited, status=1/FAILURE
droppy.service: Unit entered failed state.
droppy.service: Failed with result 'exit-code'.
```

**Comment by silverwind** [comment]
There must be some kind of error somewhere. Try running it manually as mentioned in https://github.com/silverwind/droppy/issues/323#issuecomment-320449633. If that won't work, I'd suggest reinstalling Node.js, npm and then reinstall droppy via npm.

**Comment by platipo** [comment]
As stated in [first comment](https://github.com/silverwind/droppy/issues/323#issue-248179893), there are no problems in running either the command
```
# droppy start -c /srv/droppy/config -f /srv/droppy/files

           .:.
    :::  .:::::.   droppy 6.7.0 running on node 8.2.1
  ..:::..  :::     config at /srv/droppy/config
   ':::'   :::     files at /srv/droppy/files
     '

2017-08-05 23:07:31 [INFO] Loading resources ...
2017-08-05 23:07:31 [INFO] Loading resources done
2017-08-05 23:07:31 [INFO] `uws` module failed to build, falling back to `ws`
2017-08-05 23:07:31 [INFO] Listening on http://[::]:8989
2017-08-05 23:07:31 [INFO] Caching files ...
2017-08-05 23:07:32 [INFO] Caching files done
2017-08-05 23:07:38 [INFO] Ready for requests!
```
or `/usr/bin/droppy start -c /srv/droppy/config -f /srv/droppy/files` but service keeps failing

**Comment by silverwind** [comment]
Very weird. droppy is not actually capable of exiting with error code 1 *without* any error printed. There are four cases (all in [droppy.js](https://github.com/silverwind/droppy/blob/master/droppy.js)) in the code that can result in exit code 1, and all of them log something to stderr before exiting. So either Node.js must be doing the exiting or systemd does something weird.

Maybe there is a way to debug further what systemd is doing, but I'm out of ideas except `strace`ing pid 1.

**Comment by platipo** [comment]
Any ideas? 😕

**Comment by silverwind** [comment]
You could write a shell script wrapper that is launched by systemd which in turn launches droppy. You could at least debug it better with that (like strace).

**Comment by platipo** [comment]
Journal shows nothing even though I changed droppy unit to:
```
[Unit]
Description=droppy
After=network.target

[Service]
#ExecStart=/usr/bin/droppy start -c /srv/droppy/config -f /srv/droppy/files
ExecStart=/usr/bin/strace -D /usr/bin/droppy start -c /srv/droppy/config -f /srv/droppy/files
WorkingDirectory=/srv/droppy
Environment="NODE_ENV=production"
#Restart=always
User=droppy
Group=droppy
SyslogIdentifier=droppy
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
```

**Comment by silverwind** [comment]
Try with `User=root`, strace generally only works as root.

**Comment by platipo** [comment]
Tried but no improvements, what should I do?

**Comment by silverwind** [comment]
Try the script wrapper. In the unit file:

```
ExecStart=/bin/bash /tmp/droppy-debug
```
An in `/tmp/droppy-debug`:
```
#/bin/bash
set -x
 /usr/bin/droppy start -c /srv/droppy/config -f /srv/droppy/files &>/tmp/debug
```
Then after `systemctl daemon-reload` and `systemctl restart droppy`, there should be something in `/tmp/debug` to look at.

**Comment by platipo** [comment]
This is it:
```
           .:.
    :::  .:::::.   droppy 6.8.0 running on node 8.3.0
  ..:::..  :::     config at /srv/droppy/config
   ':::'   :::     files at /srv/droppy/files
     '

2017-08-13 17:23:35 [INFO] Loading resources ...
2017-08-13 17:23:35 [INFO] Loading resources done
2017-08-13 17:23:35 [INFO] `uws` module failed to build, falling back to `ws`
2017-08-13 17:23:35 [INFO] Listening on http://[::]:8989
2017-08-13 17:23:36 [INFO] Caching files ...
2017-08-13 17:23:36 [INFO] Caching files done
```
And unit output:
```
# systemctl status droppy.service 
* droppy.service - droppy
   Loaded: loaded (/etc/systemd/system/droppy.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2017-08-13 17:23:30 CEST; 1min 43s ago
 Main PID: 22089 (bash)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/droppy.service
           |-22089 /bin/bash /tmp/droppy-debug
           `-22090 droppy
```
I'm amazed and even more confused

**Comment by silverwind** [comment]
Ah, I've been missing the fact that your output is missing the `Ready for requests!` line, which means it gets stuck somewhere before that. I'll check the code and see if there's anything that could block.

**Comment by platipo** [comment]
There are lots of files so it appeared later, I was too amazed to notice it, here it goes:
`2017-08-13 17:23:41 [INFO] Ready for requests!
`

**Comment by silverwind** [comment]
Hmm, so this still leaves us in the dark why it fails when run directly via systemd. What systemd version are you running, by the way (`systemctl --version`)?

**Comment by platipo** [comment]
```
# systemctl --version
systemd 234
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
```

**Comment by silverwind** [comment]
I got the exact same output here, so I think we have pretty much the same hardware and software. 

I'll see if I can reproduce this somehow (I run my droppy instances slightly different than what's recommend).

**Comment by silverwind** [comment]
Nope, I'm unable to reproduce. Here are my exact configs (the user was created like in the [wiki](https://github.com/silverwind/droppy/wiki/Systemd-Installation#add-user-and-group)):

#### /srv/droppy-test/config/config.json
````json
{
  "listeners": [
    {
      "host": "::",
      "port": 18989,
      "protocol": "http"
    }
  ],
  "public": false,
  "timestamps": true,
  "linkLength": 5,
  "logLevel": 2,
  "maxFileSize": 0,
  "updateInterval": 1000,
  "pollingInterval": 0,
  "keepAlive": 20000,
  "allowFrame": false,
  "readOnly": false,
  "compression": true,
  "ignorePatterns": [],
  "watch": true
}
````
#### /etc/systemd/system/droppy-test.service
````
[Unit]
Description=droppy-test
After=network.target

[Service]
ExecStart=/usr/bin/droppy start -c /srv/droppy-test/config -f /srv/droppy-test/files
WorkingDirectory=/srv/droppy-test
Environment="NODE_ENV=production"
#Restart=always
User=droppy-test
Group=droppy-test
SyslogIdentifier=droppy-test
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
````
#### systemctl status droppy-test
````
● droppy-test.service - droppy-test
   Loaded: loaded (/etc/systemd/system/droppy-test.service; disabled; vendor preset: disabled)
   Active: active (running) since Sun 2017-08-13 19:22:27 CEST; 3min 23s ago
 Main PID: 28846 (droppy)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/droppy-test.service
           └─28846 droppy

Aug 13 19:22:30 hostname droppy-test[28846]:   ..:::..  :::     config at /srv/droppy-test/config
Aug 13 19:22:30 hostname droppy-test[28846]:    ':::'   :::     files at /srv/droppy-test/files
Aug 13 19:22:30 hostname droppy-test[28846]:      '
Aug 13 19:22:30 hostname droppy-test[28846]: 2017-08-13 19:22:30 [INFO] Loading resources ...
Aug 13 19:22:30 hostname droppy-test[28846]: 2017-08-13 19:22:30 [INFO] Loading resources done
Aug 13 19:22:30 hostname droppy-test[28846]: 2017-08-13 19:22:30 [INFO] The 'uws' module failed to build, falling ba…to 'ws'
Aug 13 19:22:30 hostname droppy-test[28846]: 2017-08-13 19:22:30 [INFO] Listening on http://[::]:18989
Aug 13 19:22:30 hostname droppy-test[28846]: 2017-08-13 19:22:30 [INFO] Caching files ...
Aug 13 19:22:30 hostname droppy-test[28846]: 2017-08-13 19:22:30 [INFO] Caching files done
Aug 13 19:22:30 hostname droppy-test[28846]: 2017-08-13 19:22:30 [INFO] Ready for requests!
````

Did you alter any systemd settings perhaps? Anything uncommented in `/etc/systemd/system.conf` maybe? Another suggestion might be to check `journalctl --system -e -n 500` to see if any other units log something related when you start the service.

**Comment by silverwind** [comment]
Also, to get a bit more output when restarting services, add `LogLevel=debug` to `/etc/systemd/system.conf`, restart the service and check `journalctl --system -e -n 500`.

**Comment by platipo** [comment]
Done, these lines appeared
```
# journalctl --system -n 2 -o cat -e
/etc/systemd/system/droppy.service:17: Unknown lvalue 'LogLevel' in section 'Service'
droppy.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```

**Comment by silverwind** [comment]
You need to put it in `/etc/systemd/system.conf`, not in the service file. It's a systemd global setting.

**Comment by platipo** [comment]
It seems that the resolution was add to `/srv/droppy-test/config/config.json`
```
  "compression": true,
  "ignorePatterns": [],
  "watch": true
```
😄

**Comment by silverwind** [comment]
That shouldn't be necessary. Missing configs are automatically added to `config.json` on startup. You sure it wasn't something else?

**Comment by platipo** [comment]
I know it shouldn't, but nothing else was added than only debuging options.

**Comment by silverwind** [comment]
Weird, only thing I can think of then is that it was unable to write to that file, but such an error should be output as well.

**Comment by platipo** [comment]
It is and I actually understood what isn't working `User=droppy`, indeed I'm using `User=root`, and changing it back it stops working

**Comment by silverwind** [comment]
Try `su droppy` to run the startup command on that user. It should print something.

**Comment by platipo** [comment]
Here it goes
```
# chsh -s /bin/sh droppy
Changing shell for droppy.
Shell changed.
# su droppy
sh-4.4$ /usr/bin/droppy start -c /srv/droppy/config -f /srv/droppy/files
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/droppy/node_modules/array-unique/index.js'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.Module._extensions..js (module.js:583:20)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/droppy/node_modules/micromatch/lib/utils.js:13:16)
    at Module._compile (module.js:573:30)
```
What am I missing?

**Comment by platipo** [comment]
Reinstalled and now [your suggestion](https://github.com/silverwind/droppy/issues/323#issuecomment-322125480) works fine. Service is still failing with no additional info 😞

**Comment by silverwind** [comment]
That permission issue must be related to npm. The same file is world-readable on my system:

```
$ ls /usr/lib/node_modules/droppy/node_modules/array-unique/index.js
▕ -rwxr--r--▏silverwind:silverwind│2  day │ 512B│/usr/lib/node_modules/droppy/node_modules/array-unique/index.js
```

Can you post the debug log of systemd when starting the service? See https://github.com/silverwind/droppy/issues/323#issuecomment-322055885.

**Comment by platipo** [comment]
After beeing reinstalled mine is world-readable too
```
$ ls -l /usr/lib/node_modules/droppy/node_modules/array-unique/index.js
-rwxr--r-- 1 root root 512 Mar 25  2015 /usr/lib/node_modules/droppy/node_modules/array-unique/index.js
```
Nothing new in debug:
```
Aug 15 22:35:49 xxxx systemd[1]: droppy.service: Main process exited, code=exited, status=1/FAILURE
Aug 15 22:35:49 xxxx systemd[1]: droppy.service: Unit entered failed state.
Aug 15 22:35:49 xxxx systemd[1]: droppy.service: Failed with result 'exit-code'.
```

**Comment by platipo** [comment]
What should I do?

**Comment by platipo** [comment]
After the last update it seems the problem is vanished
