### ISSUE TITLE
Throwing error when --daemon option applied

### ISSUE THREAD

**Issue by t-k-** [silverwind/droppy#324]
Hi, when I add a `--daemon` option to droppy, an error is thrown:
```
node ./node_modules/droppy/droppy.js -f ~/Desktop/ --daemon start
child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at Object.exports.spawn (child_process.js:487:38)
    at Function.module.exports.daemon (/home/tk/node_modules/daemon/index.js:50:31)
    at module.exports (/home/tk/node_modules/daemon/index.js:25:20)
    at Object.<anonymous> (/home/tk/node_modules/droppy/droppy.js:45:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I am using 6.7.1 droppy, but it seems older version like 6.3.18 has this problem too. My operation system has just reinstalled, I recall that I do not get this error before, strange. Any idea?

**Comment by t-k-** [comment]
Relevant clue I have found after googling around:
https://github.com/NodeBB/NodeBB/issues/5780

Perhaps this is the reason? I am not sure, but looks like very much the case.

**Comment by silverwind** [comment]
Spot on, it's a bug in the daemon module that also caused it to use the wrong working directory. I updated to the fork, but am looking for a replacement module for later.
