### ISSUE TITLE
TypeError: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by Kilims** [silverwind/droppy#338]
Hi My node, npm and droppy version:
- node v7.7.2
- npm v4.0.5
- droppy v8.0.3

I had run this command:
`npm i -g --production droppy`
which is succeed and I run this command :

`droppy start -f J:/learning`
which is existing in my PC,

when I access to `http://localhost:8989`
I can have the login page. 
but after login, it shows this error:

2018-03-15 00:26:27 [ERROR] TypeError: Cannot read property 'files' of undefined
    at D:\node\node_modules\droppy\server\filetree.js:345:39
    at Array.forEach (native)
    at entries (D:\node\node_modules\droppy\server\filetree.js:344:9)
    at EventEmitter.filetree.ls (D:\node\node_modules\droppy\server\filetree.js:394:10)
    at sendFiles (D:\node\node_modules\droppy\server\server.js:714:23)
    at D:\node\node_modules\droppy\server\server.js:517:11
    at D:\node\node_modules\droppy\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:114:15)

Can help to fix it ?

**Comment by silverwind** [comment]
Can you check if starting with a lowercase drive letter, like `droppy start -f j:/learning` makes any difference?

**Comment by silverwind** [comment]
Nevermind, I reproduced. Looks to be something Windows-specific.
