### ISSUE TITLE
Error when trying to start droppy

### ISSUE THREAD

**Issue by hildebro** [silverwind/droppy#411]
Trying to run droppy like so:
`/usr/bin/env droppy start -c /path/to/conf -f /path/to/files`

Resulting in the following error:
```
           .:.
    :::  .:::::.   droppy 11.1.0 running on node 14.3.0
  ..:::..  :::     config at /path/to/conf
   ':::'   :::     files at /path/to/files
     '

[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (2748)
    at writeFile (fs.js:1356:5)
    at go$writeFile (/usr/lib/node_modules/droppy/node_modules/graceful-fs/graceful-fs.js:139:14)
    at Object.writeFile (/usr/lib/node_modules/droppy/node_modules/graceful-fs/graceful-fs.js:136:12)
    at async.series.ready (/usr/lib/node_modules/droppy/server/server.js:69:41)
    at /usr/lib/node_modules/droppy/node_modules/async/dist/async.js:3880:24
    at replenish (/usr/lib/node_modules/droppy/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/usr/lib/node_modules/droppy/node_modules/async/dist/async.js:995:17)
    at /usr/lib/node_modules/droppy/node_modules/async/dist/async.js:969:16
    at /usr/lib/node_modules/droppy/node_modules/async/dist/async.js:3885:13
    at /usr/lib/node_modules/droppy/node_modules/async/dist/async.js:473:16
```

**Comment by hildebro** [comment]
I solved the problem by using node 12 LTS instead of the newest node 14 version.

Only reason I tried an older version was that I reinstalled droppy and got deprecation warnings from dependency packages. 
Would be nice, if droppy kept track of the latest supported version and gave a more helpful error when the node version is too recent.
